### ISSUE TITLE
Subject Conversion Test: Stage 2

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#178]
### Data input
File: [stage_2_data_input_test.xlsx](https://github.com/ucsdlib/damsmanager/files/1402830/stage_2_data_input_test.xlsx)

Includes columns:

1. record_type  
2. updated_label
3. external_authority_URI
4. wikipedia_URI
5. other_URI
6. variant_label 

### Matching criteria
`data input "updated_label" EXACT match to DAMS authoritativeLabel` _(NO fuzzy searching, trimming whitespace, etc.)_ 
**AND**
`data input "record_type" match to DAMS authority record type`

### Process
1. Match all authority records against criteria above 
	1. IF there is an exact match on all criteria (AND/&&) 
		1. return “first” current DAMS ARK
		2. Update existing authority record of the returned DAMS ARK with:
			1. external_authority_URI => mads:hasExactExternalAuthority
			2. wikipedia_URI => mads:hasCloseExternalAuthority
			3. other_URI => mads:hasBroaderExternalAuthority
			4. variant_label => mads:hasHiddenVariant
	2. ELSE
		1. create a new authority record 
			1. updated_label => authoritativeLabel
			2. external_authority_URI => mads:hasExactExternalAuthority
			3. wikipedia_link => mads:hasCloseExternalAuthority
			4. other_URI => mads:hasBroaderExternalAuthority
			5. variant_label => mads:hasHiddenVariant
		2. return DAMS ark

### Output
Report on results, including:
* Record type
* Label
* Action taken:
    * created - _for new records created_
    * matched - _for records matched but not updated_
    * updated - _for records that are matched and updated_
* ARK

### Related work
Dependent on: Subject Conversion Test: Stage 1 https://github.com/ucsdlib/damsmanager/issues/177
Overall subject conversion process https://github.com/ucsdlib/damspas/issues/355

**Comment by arwenhutt** [comment]
@lsitu @gamontoya @mcritchlow 
This is ready now (wasn't sure who to ping, so just letting you all know)

**Comment by lsitu** [comment]
@arwenhutt For the report, do you just need the records that are updated when matches are found? Or you would prefer to include all records that are matched in the report but marking it as matched or updated in the "Action taken" column?

**Comment by arwenhutt** [comment]
@lsitu good question, we need an ark back for all records so we can integrate into the next stage, so your second option would be best. I’ll update the description of the report to reflect that. 
Thanks!

**Comment by lsitu** [comment]
@arwenhutt Yep, thanks. I've added those matched records to the report. I also added the Row# column so that you can reference it in the source file. All 9916 authority records are updated/created on QA now. 
Attached is the report:
 
[report-subjects.txt](https://github.com/ucsdlib/damsmanager/files/1407652/report-subjects.txt)

Here are some examples (record created with bd arks instead of bb arks on prod):
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bb3312070b (Row#4 record updated)
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bd6604326b (Row#532 record created)
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bb10595460 (Row#891 record updated)
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bb0683976n (Row#1687 record updated)
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bb7851367w (Row#2049 record updated)
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bd9198210k (Row#7287 record created)
http://lib-hydratail-qa.ucsd.edu:8080/dams/api/objects/bb1163173b (Row#9518 record updated)

**Comment by arwenhutt** [comment]
Thanks @lsitu this looks good overall, but there's one thing we need changed:

For the report, we need a single ark per unique label even if there are multiple matches in the database (1.i.a.).  
* When the record is updated (1.i.b.) that ark should be used
* When no record is updated (in the case there is a label match but no additional metadata to add), any single ark for one of the duplicate authority records can be used

The output report should have a 1:1 alignment with the data input file on unique label values and total number of rows.

**Comment by lsitu** [comment]
@arwenhutt I've generated the 1:1 alignment report. It includes an additional column "Duplicate ARK" for those records that are matched but not updated (delimited by | ). Just noted that the records updated in the ARK column may not be exactly as last time if there are multiple matches (duplicates) , so we may need to use the ARKs in this report for next stage and stages following for records re-linking/clean up.
Here is the updated report:
[report-subjects.txt](https://github.com/ucsdlib/damsmanager/files/1411479/report-subjects.txt)

**Comment by lsitu** [comment]
@arwenhutt I think I just added the note for the the potential use of the ARK column and the Duplicate ARK column in the report above, so that we all are in the same page  not to reference/use the report I attached yesterday in [#issuecomment-338705530](https://github.com/ucsdlib/damsmanager/issues/178#issuecomment-338705530). 

- For stage 3, I think if you already have a full list of the old_ARK that includes all ARKs in the Duplicate ARK column, then those duplicate ARKs (matched but not updated authority records) could be ignored.
- For stage 4, the rules seem quite complicate to me and I think it'll be nice if you can provide an example source input so that I can think about it in the implementation level.
- For clean up  (stage 5), I think it looks clear enough to just remove some old links from CLRs and OLRs.

**Comment by arwenhutt** [comment]
@lsitu 
> so that we all are in the same page not to reference/use the report I attached yesterday in #issuecomment-338705530.
Got it! yep, same page :)

> For stage 4
I'm still working on the easiest way to approach this one, the gray text there is just outlining some of the complexity of the problem in case anyone else had a brainstorm on how to tackle it, it's not meant for implementation.  I think it will still probably be the most difficult stage, but it will have processing steps outlined like the other steps when it's ready.   I'll ping you when I have a draft of it ready for review.

> For stage 5
Great!

**Comment by arwenhutt** [comment]
@lsitu it looks like there's a problem with the character encoding in the report, e.g.
`Viti︠a︡zʹ`
comes out as 
`Viti?a?z?`

**Comment by lsitu** [comment]
@arwenhutt Let me take a look and see how to fix it.

**Comment by lsitu** [comment]
@arwenhutt I think I've fixed the character encoding problem in the report. Those corrupted diacritics with question marks are updated and around 40 of the total 9916 records/ARKs are corrected to use the existing bb ARKs in stead of creating new records with bd ARKs. Here is the updated report:
[report-subjects.txt](https://github.com/ucsdlib/damsmanager/files/1415225/report-subjects.txt)

**Comment by arwenhutt** [comment]
@lsitu thanks!  I'll work on the input file and issue ticket for stage 3 today.

**Comment by arwenhutt** [comment]
@lsitu I'm still seeing weird character encoding errors in the new report
The example above is now `Vitiï¸ aï¸¡zÊ¹`

It looks correct in the authority record though.

**Comment by gamontoya** [comment]
I see this @arwenhutt `"Viti︠a︡zʹ" (Ship)`

**Comment by arwenhutt** [comment]
Ah! So maybe this time it’s excel :) I checked the txt last time but not this time. Thanks!

**Comment by gamontoya** [comment]
Yes Excel is a grouch and a pain if you don't import UTF-8 in the steps it wants you to. Let me know if you need help with this.

![excel](https://user-images.githubusercontent.com/4314914/32017867-ecdf91fa-b97c-11e7-8df4-c6aa919b3f2c.png)

**Comment by arwenhutt** [comment]
@gamontoya yup! I usually check that, just made the incorrect assumption that since it was the data file last time it was the data file this time :)  working on creating the data input file now.
