### ISSUE TITLE
DAMS Manager is not reporting RDCP Views when clicking in from URL

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#192]
### Descriptive summary

Visits to object pages from users in both curator and non-curator mode do not get logged in RDCP stats reports (https://library.ucsd.edu/damsmanager/statsRdcpUsage.do) when the URL is directly clicked from linked text, such as https://library.ucsd.edu/dc/object/bb73062290.

### Expected views
We tested view counts for about 15 unique objects and found that none were reported by DAMS Manager. 
Below is a sample of the objects tested:
Commitment Problems -- 1
Bangarang -- 4
Automation -- 1

### Actual views
Commitment Problems -- 0
Bangarang -- 0
Automation -- 0

### Steps to reproduce the behavior

1. Use Chrome in normal (not incognito) mode.
2. Click on the following URLs, saved on an external doc or spreadsheet:
- Commitment Problems https://library.ucsd.edu/dc/object/bb73062290
- Bangarang https://library.ucsd.edu/dc/object/bb5975373f
- Automation https://library.ucsd.edu/dc/object/bb6419296g
3. Leave pages.
4. Check https://library.ucsd.edu/damsmanager/statsRdcpUsage.do the next day.

### Related work
As an aside, we clicked on 5 hyperlinked DOIs to visit 5 unique objects, and none were reported as RDCP Views by DAMS manager.

**Comment by hjsyoo** [comment]
@anrastog

**Comment by lsitu** [comment]
@hjsyoo When did you run the tests? Do you get the counts when you test it directly on dams public page https://library.ucsd.edu/dc by browsing and searching?

I am trying to understand what might be an issue since I see lots of counts showing up in https://library.ucsd.edu/damsmanager/statsRdcpUsage.do for those objects tested recently.

Commitment Problems https://library.ucsd.edu/dc/object/bb73062290:
2017/10: 4 0
2017/11: 2 0
<img width="1438" alt="screen shot 2017-11-28 at 11 21 53 am" src="https://user-images.githubusercontent.com/2430784/33339586-80c3dedc-d42e-11e7-896c-e281e8b35b9c.png">

Bangarang https://library.ucsd.edu/dc/object/bb5975373f:
2017/10: 7 0
2017/11: 18 0
<img width="1440" alt="screen shot 2017-11-28 at 11 19 15 am" src="https://user-images.githubusercontent.com/2430784/33339450-0c445e42-d42e-11e7-855a-544b134a136a.png">

Automation https://library.ucsd.edu/dc/object/bb6419296g:
2017/08: 2 2
2017/09: 2 0
2017/10: 8 0
2017/11: 22 0 
<img width="1439" alt="screen shot 2017-11-28 at 11 03 15 am" src="https://user-images.githubusercontent.com/2430784/33338779-f3d8f338-d42b-11e7-9952-523e38d8faee.png">

**Comment by hjsyoo** [comment]
When we get to an object by browsing or searching from within https://library.ucsd.edu/dc, the counts do indeed get logged. But when we click on a URL we have copied onto a spreadsheet previously, such that we go directly to the object without browsing, the visit does not get logged. I suspect the same log failure occurs when finding the link through a search engine, although we haven't tested this explicitly. We have tested whether clicks on DOIs get logged, and we find the same logging failure occurs. I suspect that we are missing a lot of visits in the stats reports, because many research data collections will be discovered from links in (external) publications/articles or via search engine. I didn't realize there was this distinction in logging behavior. So I was confused because I thought it was working a year ago (when I tested by browsing to objects), but then found in July/Aug that my views were not getting logged (when I tested by clicking on URLs I saved on a spreadsheet). I have project assistants working with me now who helped identify the underlying issue. I'll make a minor edit to the ticket description to clarify this.

**Comment by lsitu** [comment]
@hjsyoo Thank you very much for the clarification. I did some tests yesterday to click on the object URL above and I see the object URL is logged in the weblog. And this morning I see the counts for RDCP Views increase in https://library.ucsd.edu/damsmanager/statsRdcpUsage.do: 
Commitment Problems
2017/11: 4 0 (was 2 0) 

Bangarang https://library.ucsd.edu/dc/object/bb5975373f:
2017/11: 32 0 (was 18 0)

Automation https://library.ucsd.edu/dc/object/bb6419296g:
2017/11: 34 0 (was 22 0)

So I believe the problem you see should be gone now. Could you test it again? Please record the date time that your test is performed so that we can track it down. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Sorry, it turns out your test was confounded by the fact that @anrastog and @xiw391 were running some tests on those same objects yesterday. But they're now noticing that another set of objects that they clicked into via URL are getting logged and reported by DM. This is not the behavior they were seeing prior to yesterday. Did you apply any fixes yesterday, or were you only testing?

**Comment by lsitu** [comment]
@hjsyoo We haven't deployed damsmanager for some times already. And we didn't made any changes for RDCP status since you reported the missing counts a few months before due to the https logging change. 
However, if your tests was happened to be performed on Monday, Oct. 16, it won't get counted until we deploy the new release for damsmanager to prod.

**Comment by hjsyoo** [comment]
@lsitu All of our testing has been done since Oct 25. We've seen views being counted when visiting pages by browsing. We've also seen downloads being counted correctly. Can you clarify what isn't working at present but will be when the new release is deployed?

**Comment by lsitu** [comment]
@hjsyoo That sounds good. I think all features for RDCP status should be working at this time. The new release is just to fix an issue with the invalid URL so that we can have the stats counted for Oct. 16.

**Comment by hjsyoo** [comment]
@lsitu Okay, that's good to hear. But I think the problem remains that direct entry into objects don't get logged consistently (there are some objects that do, and some that log too many views - we're investigating that now). If you'd like to check from your end, here are a few pages that we won't be testing this week:
https://library.ucsd.edu/dc/object/bb9491049c (CAICE)
https://library.ucsd.edu/dc/object/bb38595979 (CAICE)
https://library.ucsd.edu/dc/object/bb47126209 (SOCCOM)
https://library.ucsd.edu/dc/object/bb4985739g (SOCCOM)

**Comment by hjsyoo** [comment]
I can also provide a detailed log of our activity if you think it would help, but I want to clean it up and make sure it's comprehensible.

**Comment by lsitu** [comment]
@hjsyoo Thanks. That could be helpful if you see something that was not counted as expected.
I'll test the first object https://library.ucsd.edu/dc/object/bb9491049c (CAICE):
I see the following counts at this time:
2017/10: 11 12
2017/11:   1 0
<img width="1440" alt="screen shot 2017-11-29 at 2 36 08 pm" src="https://user-images.githubusercontent.com/2430784/33402930-2b5f4d10-d513-11e7-9176-7f49495258d8.png">

**Comment by lsitu** [comment]
@hjsyoo I see the counts increase for object https://library.ucsd.edu/dc/object/bb9491049c (CAICE):
2017/11: 2 0 (was 1 0)
<img width="1439" alt="screen shot 2017-11-30 at 8 24 55 am" src="https://user-images.githubusercontent.com/2430784/33441763-4db6c3bc-d5a8-11e7-82a6-282cb12dde41.png">

Please keep in mind that DAMS Statistics won't be able to count it if your browser loads the object page from its cache when you view the same page the second time with the same browser.

**Comment by hjsyoo** [comment]
Ok, I didn't realize that, but @anrastog clears her cache at the end of each day. We've been running tests over multiple days.
Also, I have just done a similar test for the CAICE object you tested yesterday, but in incognito. Will let you know what I get tomorrow.

**Comment by lsitu** [comment]
@hjsyoo Thanks. Please close the browser and open a new incognito browser each time when you run a test for the same object URL. You may not get everything counted if you only clear the browser's cache at the end of the day.

**Comment by hjsyoo** [comment]
@lsitu I just shared a google sheet with you: https://docs.google.com/spreadsheets/d/1JWic6IF1e3yswqqNmOxxFy35lIwuhu7_Kbuvz62ynbs/edit#gid=1673736810. See tab, "Testing URL direct links". This is a record of tests we ran for clicking on URLs to open object pages. The "Action" column F describes what we did, and Expected and Observed reports are to the right. The + sign after counts simply indicates the increment that we expected or observed. For example, if the month-to-date number of views for an object is currently 10, and we click into the object once today, then tomorrow's expected views would be "1+" (i.e., 11). We don't bother reporting the 10 and 11.
Note that a minority of objects did register views. We're currently investigating whether this is consistent behavior for those particular objects, or if it's likely that someone else visited the page that day.

**Comment by lsitu** [comment]
@hjsyoo It looks good. Thanks.
To avoid the annoying caching issues that may affect your expected counts, please close the browser and open an incognito one **each time** when you test a file download or object URL view. Thanks.

**Comment by gamontoya** [comment]
@hjsyoo Can this be closed out? I'm assuming you'll be creating new "related" tickets?

**Comment by hjsyoo** [comment]
Yes, closing this ticket.
